### ISSUE TITLE
Prohibit magic number arguments to unary methods

### ISSUE THREAD

**Issue by AgentAntelope** [Bodacious/no-magic-numbers-cop#10]
We want to prohibit code like

```@ruby
days = hours * 24
```

**Comment by Bodacious** [comment]
Do we want to extend this to other mathematical operators?

``` ruby 
# bad 
day_of_week = total_number_of_days % 7

# good
day_of_week = total_number_of_days % DAYS_IN_WEEK
```

**Comment by AgentAntelope** [comment]
I think we should probably make it all unary methods, if possible, to avoid missing any (and to support future changes)
