### ISSUE TITLE
Relax ruby requirement to 3.0

### ISSUE THREAD

**Issue by hlascelles** [Bodacious/no-magic-numbers-cop#61]
Currently ruby 3.2 [is required](https://github.com/meetcleo/rubocop-magic_numbers/blob/main/rubocop-magic_numbers.gemspec#L19).

Is this necessary? 3.0 is no yet EOL.

Can do a PR unless there is a reason!

**Comment by Bodacious** [comment]
This was fixed in https://github.com/meetcleo/rubocop-magic_numbers/pull/62 by @marian13
