### ISSUE TITLE
Invalid syntax on readme

### ISSUE THREAD

**Issue by evanthegrayt** [Bodacious/no-magic-numbers-cop#63]
I was reading about this gem via the readme, and thought the syntax under the [MagicNumbers/NoDefault](https://github.com/meetcleo/rubocop-magic_numbers#magicnumbersnodefault) section looked incorrect. I checked it using version 3.2.2, and I do indeed get errors.

```ruby
def over_widget_limit?(20)
  # ...
end
# SyntaxError: unexpected integer literal, expecting ')'
# def over_widget_limit?(20)
#                        ^~

def over_widget_limit?(FREE_SUBSCRIPTION_WIDGET_MAX)
  # ...
end
# (eval):2: formal argument cannot be a constant
# ...t?(FREE_SUBSCRIPTION_WIDGET_MAX)
# ...   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm not sure what the correct usage should be, but I assume either method _calls_?

```ruby
# BAD
over_widget_limit?(20)

# GOOD
over_widget_limit?(FREE_SUBSCRIPTION_WIDGET_MAX)
```

...or method definitions with a default?

```ruby
# BAD
def over_widget_limit?(max = 20)
  # ...
end

# GOOD
def over_widget_limit?(max = FREE_SUBSCRIPTION_WIDGET_MAX)
  # ...
end
```

**Comment by Bodacious** [comment]
Thanks @evanthegrayt. I've updated the README now
