### ISSUE TITLE
Build in support for Migrations

### ISSUE THREAD

**Issue by hlascelles** [Bodacious/no-magic-numbers-cop#67]
We are seeing errors for these "array" methods in migrations:

```ruby
class Foo < ActiveRecord::Migration[6.1] # Here
end
```

This probably affects a lot of people. Can it be made to ignore implicitly? Or make it a default "enabled" ignore?

i'd rather not disable `[]` or the number `6.1`.

What do you think?

**Comment by adesnmi** [comment]
Hey @hlascelles, could you provide a sample rubocop config and/or file that causes this issue?

I tried creating a new rails app and (after auto-correcting some default errors), there weren't any errors specific to this gem.

The default config tries to handle the case you specified via:

```
IgnoredMethods:
    - '[]' # defaults to just the #[] method
```

Let me know if I missed anything.

**Comment by hlascelles** [comment]
Given:

```ruby
class Foo < ActiveRecord::Migration[6.1]
  new_price = PRICE_LIST[42]
  Widgets.update_all(price: new_price)
end
```

Here the Migration `6.1` isn't *really* magic (or maybe it is, subjectively! :)). It is just the Rails version to us. We'd rather not mark them all as non-magic.

The `PRICE_LIST[]` call (to `[]`) is definitely magic, and needs explaining.

I guess what I'd like is this new config to exist, where not just the method name, but also the class it is on can be specified.
Note, `[]` is not ignored! We want it to fire in general.

```yaml
MagicNumbers/NoArgument:
  IgnoredMethods:
  - ActiveRecord::Migration[]
```

This cop would fire on `foo[42]` but not `ActiveRecord::Migration[42]`

**Comment by Bodacious** [comment]
Hi @hlascelles 

I think the fastest way of achieving what you want in this case is to simply exclude the migrations directory from the cop config.

``` yaml
MagicNumbers/NoArgument:
  Exclude:
    - db/migrate/*.rb
```

Of course, this won't police the magic number in the example you gave, but this might not be the best example, as migrations are only really intended to create schema changes (and not data changes).

I can see this issue bothering more users who have installed the gem in a Rails app, so I'll make a separate PR now to update the README.md to warn against this.

I think the decision to include this as a default in the gem's configuration warrants further discussion, as this gem isn't limited to only Rails applications. 

If you wanted to have a go at extending the functionality to allow for configuration of specific methods, then I would welcome a PR, but I don't think there's much capacity for the gem owners to make that update right now.
